### ISSUE TITLE
HOST_IP:8080/paraview/ No Such Resource

### ISSUE THREAD

**Issue by aabdulwahed** [Kitware/light-viz#61]
Hello,

I've installed Paraview v5.2 and Light-Viz on Ubuntu 14.04 LTS... after starting the server as following 

<code>$ LightViz --paraview /opt/ParaView/ --data ~/data/</code>

The page doesn't load successfully!!. Also I got <code>"No such resource"</code> message and I can notice from console that server unable to access this "HOST_IP:8080/paraview/".

Looking forward to hear from you!

Thanks,
Ahmed

**Comment by jourdain** [comment]
The "HOST_IP:8080/paraview/" error is expected when starting LightViz from the command line since the launcher is not involved.

The loaded page should be all black with 2 buttons on the top left.

Then depending on what ~/data contains you may see more, but you will need to register the datasets in order to see them.

If you are using the `data` directory from ParaView, you should do the following to add them.

```sh
$ mkdir ~/LightViz-datasets
$ LightViz --add-dataset ~/data/can.ex2                --description "" --data ~/LightViz-datasets
$ LightViz --add-dataset ~/data/disk_out_ref.ex2  --description "" --data ~/LightViz-datasets
$ LightViz --data ~/LightViz-datasets
```

**Comment by aabdulwahed** [comment]
Thanks Seb! ....The issue solved ..
